version: '3'
services:
    nginx:
        restart: always
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - php-fpm

    php-fpm:
        restart: always
        build: ./docker/php-fpm
        expose:
            - "9000"
        volumes:
            - ./:/var/www/html
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

    mysql:
        restart: always
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /home/ayuna/docker/blog/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_ROOT_PASSWORD=root
